#!/bin/env bash
# iarom mail@iarom.org
# backup meta script with device specs

ini()
{
    [ -f ${BHQC} ] \
        || { echo "missing bhq config; exiting"; exit; }
    source ${BHQC}
    _env_bhq
    _notif_env
}

prnt()  { printf "BHQ: %s\n" "#" "$1"; }
prntx() { printf "BHQ: %s\n" "$1"; }
notif() { notify-send -u low "${lineh}" "${linex}"; }

_bk_sys_ini()
{
    _bk_sys_pre
}

# bksq

_dev_lcb_sys()      { _bk_sys_ini;  }
_dev_rma_min()      { yes | rst gcs bpmin; } # remote - part.min

# compounds

# - [ ] basic fs backup of important dirs to devices as an rsync sync
#     - to host a copy

_dev_lca_vcs_aaa()
{ 
    prnt "init bkp ->'''lca'''"
    rst lca bpmin       # local vcs/snapshots
    rst lca vc-xds      # vcs of surf media
}

_dev_dva_a()
{
    prnt "init bkp ->'''dva'''"
    brg dva bf
    kys dva exp
    #rsn dva  # sudo req #rs dva.pmin # sol?
} 

_dev_dvb_a()
{
    prnt "init bkp '''dvbs'''"
    brg dvb bf
    kys dvb exp
    #rsn dvb #rs dvb.pmin
}

_dev_dvb_b()
{
    prnt "init bkp ->'''dvb'''"
    brg dvb backup-mid
    #rsn dvb #rs dvb.pmin
}

_dev_dvc_a()
{
    prnt "init bkp ->'''dvc'''"
    kys dvc exp
}

_dev_dvd_a()
{
    prnt "init bkp ->'''dvd'''"
    kys dvd exp
}

_dev_dve_a() { echo "";} # todo

# schedules

_reg_aaa() {
    _dev_lcl_vcs_xaa
}

_reg_aab()
{
    prnt "backup '''essentials'''"
    _lcl_vcs_aaa
    _rem_par_min
    _notif
}

main()
{
    cmd="${1}" && shift 1
    ini

    case ${cmd} in
        tga)      _reg_aaa ;;
        tgb)      _reg_aab ;;
        laa)      _dev_lcl_vcs_aaa ;;
        raa)      _dev_rem_par_min ;;
        # selectors
        rma)      _dev_rem_raa ;;
        lca)      _dev_lcl_laa ;;
        dva)      _dev_dva_a ;;
        dvb)      _dev_dvb_a ;;
        dvc)      _dev_dvc_a ;;
        # maintenance
        pre)      _bk_sys_ini ;;
        notif)    notif ;;
        *)        $(@) ;;
    esac
}

main "${@}"
