#!/bin/env bash
# iarom mail@iarom.org
# backup meta script with device specs

# targets such as plugin storage devices, remote cloud target, local machine
# methods/types such as brg, rst, keys
# groups of methods per targets
# schedules for remote or locally accessible
# automations for autmounted/mounted plugin storageA
# TASK basic fs bkp of important dirs to devices iva eg rsync
# TASK probably better to the content here config like
# it heavily refers to user level custom cmds
# TASK update schedules

ini()
{
    [ -f ${BHQC} ] \
        || { echo "missing bhq config; exiting"; exit; }
    source ${BHQC}
    _env_bhq
    _notif_env
}

prnt()  { printf "BHQ: %s\n" "#" "$1"; }
prntx() { printf "BHQ: %s\n" "$1"; }
notif() { notify-send -u low "${lineh}" "${linex}"; }

_bk_sys_ini()
{
    _bk_sys_pre
}

# bksq

_lcb_sys()      { _bk_sys_ini;  }
_rma_rst_min()  { yes | rst gcs bpmin; } # remote part min

# compounds

_lca_vcs_a()
{ 
    # local rst now outdated
    # TASK setup btrfs snapshots
    prnt "init bkp ->'''lca'''"
    #rst lca bpmin       # local vcs/snapshots
    #rst lca vc-xds      # vcs of surf media
}
_dva_a()
{
    prnt "init bkp ->'''dva'''"
    brg dva bf
    kys dva exp
    #rsn dva  # sudo req #rs dva.pmin # sol?
} 
_dvb_a()
{
    prnt "init bkp '''dvbs'''"
    brg dvb full
    kys dvb exp
    #rsn dvb #rs dvb.pmin
}
_dvb_b()
{
    prnt "init bkp ->'''dvb'''"
    brg dvb backup-mid
    kys dvb exp
    #rsn dvb #rs dvb.pmin
}
_dvc_a()
{
    prnt "init bkp ->'''dvc'''"
    kys dvc exp
}
_dve_a() { echo "";} # todo
_dvx_a()
{
    prnt "init bkp ->'''dvx'''"
    kys dvx exp
}

# schedules

_reg_aaa() {
    _lcl_vcs_x
}
_reg_aab()
{
    prnt "backup '''essentials'''"
    _lca_vcs_a
    _rma_rst_min
    _notif
}

main()
{
    cmd="${1}" && shift 1
    ini
    case ${cmd} in
        tga)      _reg_aaa ;;
        tgb)      _reg_aab ;;
        laa)      _lcl_vcs_aaa ;;
        raa)      _rem_par_min ;;
        # local/remote selectors
        rma)      _rem_raa ;;
        lca)      _lcl_laa ;;
        # dependent on device plugs
        dva)      _dva_a ;;
        dvb)      _dvb_a ;;
        dvc)      _dvc_a ;;
        dvx)      _dvx_a ;;
        # maintenance
        pre)      _bk_sys_ini ;;
        notif)    notif ;;
        *)        $(@) ;;
    esac
}
main "${@}"
