#!/usr/bin/env bash

# Iarom Madden mail@iarom.org

# borg wrapper
# - [x] move some of below to config files
#declare -g hostname="${HOST}"

set -e -o pipefail

ini()
{
    declare -g args=()
    declare -g opt=()

    [ -f ${BHQC} ] \
        || { echo "missing bhq config; exiting"; exit; }

    source ${BHQC}
    _env_bhq
}

prn_l()     { printf "\n"; }

prn_h()     { printf "BRG: %s \n" " " "${1}"; }

prn()       { printf "BRG: %s \n" "${1}"; }

prn_args()
{
    prn_l; prn_l
    prn "borg"
    shift 1
    printf "BRG:   %s \n" ${args[@]}${YELLOW}
    prn_l
}

env_set()
{
    ${1}
    prn_l; prn "${BHQ_DEV}: ${BORG_REPO} {${BORG_PASSCOMMAND}}"
}

env_set_rem()
{
    # todo
    nm_mobile && exit 1 #todo: exit function printing message
    env_set "${1}"
}

brg_cmd() { exec borg "${args[@]}"; }

set_rep()
{
    case "${rep}" in
        dva)  env_set "_env_dva"  ;;
        dvb)  env_set "_env_dvb"  ;;
        dvx)  env_set "_env_dvx"  ;;
        lca)  env_set "_env_lca"  ;;
        wasa) env_set "_env_r_wia" ;;
        wasb) env_set "_rem_r_wib" ;;
        *)    prn "repo required" && exit
    esac
}

set_cmd()
{
    case ${cmd} in
    xx|custom)
        prn "custom command: ${@}" ""
        args+=( "${@}" )
        ;;

    in|init)
        prn "init" ""
        args+=( 'init' )
        args+=( '--encryption' 'repokey-blake2' )
        args+=( "${@}" )
        ;;

    mn|mount|mnt|m)
        prn "mount: ${BORG_MOUNTPOINT}" ""
        args+=( 'mount' )
        args+=( "${BORG_REPO}" )
        args+=( "${BORG_MOUNTPOINT}" )
        ;;

    un|umount|umnt)
        prn "umount: ${BORG_MOUNTPOINT}" ""
        args+=( 'umount' )
        args+=( "${BORG_MOUNTPOINT}" )
        ;;

    bf|backup-full|full)
        prn "src: full '${SRC}/'" \
            "exl: ${BHQ_EXL_AAX}:" \
            ""
        args+=( 'create' )
        args+=( '--stats' )
        args+=( '--progress' )
        args+=( "--exclude-from" "${BHQ_EXL_AAX}" )
        args+=( "::'$(date +%y.%m.%d.%H.%M)'" )
        args+=( "${SRC}/" )
        args+=( "${@}"     )
        ;;

    bm|backup-mid|bk-mid)
        prn "src: partial.mid '${SRC}/'" \
            "exl: ${BHQ_EXL_AAX}"
            "exl: ${BHQ_EXL_ABX}"
        args+=( 'create' )
        args+=( '--stats' )
        args+=( '--progress' )
        args+=( "--exclude-from" "${BHQ_EXL_AAX}" )
        args+=( "--exclude-from" "${BHQ_EXL_ABX}" )
        args+=( "::'$(date +%y.%m.%d.%H.%M)'" )
        args+=( "${SRC}/" )
        args+=( "${@}" )
        ;;
  
    part)
        #"Partial Home Backup # TODO
        ;;

    *) prn "no cmd" && exit
        ;;

    esac
}

main()
{
    rep="${1}"; cmd="${2}"; shift 2
    ini

    set_rep
    set_cmd "${@}"

    prn_args
    brg_cmd
}

main "${@}"
