#!/usr/bin/env bash

# Iarom Madden mail@iarom.org

# borg wrapper

set -e -o pipefail
rep="$1"
cmd="$2"
shift 2

args=()
opt=()

bkhq_d="${HOME}/.config/bkhq"

#todo: move some of below to config files

exl_a="${bkhq_d}/exla"
exl_b="${bkhq_d}/exlb"
icl="${bkhq_d}/inc"
icl_part_mid="${bkhq_d}/inc-bxx"
icl_part_min="${bkhq_d}/inc-min"
icl_part_mst="${bkhq_d}/inc-mst"

brg_mnt="${HOME}/.local/share/aaa/mnt/xbk-brg/"

hostname="${HOST}"

env_dva="${bkhq_d}/env-dva"
env_dvb="${bkhq_d}/env-dvb"
env_dvx="${bkhq_d}/env-dvx"
env_lca="${bkhq_d}/env-lca"

src="/dat"

blue=$(tput setaf 4)
normal=$(tput sgr0)
yellow=$(tput setaf 3)

prn_l()     { printf "\n"; }

prn_h()     { printf "BRG: %s \n" "################################" "${1}"; }

prn()        { printf "BRG: %s \n" "${1}"; }

prn_args()
{
    prn_l
    prn "${1}"
    shift 1
    printf "BRG:   %s \n" "${@}"
    prn_l
}

env_set()
{
    . ${1}
    prn_l
    prn "${2}: ${BORG_REPO} {${BORG_PASSCOMMAND}}"
}

env_set_rem()
{
    # todo
    nm_mobile && exit 1
    env_set "${1}" "${2}"
}

case "${rep}" in
    dva) env_set ${env_dva} "device_a" ;;
    dvb) env_set ${env_dvb} "device_b" ;;
    dvx) env_set ${env_dvx} "device_x" ;;
    lca) prn "lca: TODO" && exit
            env_set ${env_lca} "local_a" ;;
    was.a) prn "was.a is TODO \n" && exit
            env_set_rem ${rem_was} "wasabi_a" ;;
    *) prn "repo required" && exit
esac

case ${cmd} in
    xx|custom)
        prn "choose a custom command.." ""
        args+=( "${@}" )
        ;;

    in|init)
        prn "init" ""
        args+=( 'init')
        args+=( '--encryption' 'repokey-blake2')
        args+=( "${@}" )
        ;;

    mn|mount|mnt|m)
        prn "mount: ${brg_mnt}" ""
        args+=('mount')
        args+=("${BORG_REPO}")
        args+=("${brg_mnt}")
        ;;

    un|umount|umnt)
        prn "umount: ${brg_mnt}" ""
        args+=('umount')
        args+=("${brg_mnt}")
        ;;

    bf|backup-full|full)
        prn "src: full '$src/'" \
            "exl: ${exl_a}:" \
            ""
        args+=( 'create' )
        args+=( '--stats' )
        args+=( '--progress' )
        args+=( "--exclude-from" "$exl_a")
        args+=( "::'$(date +%y.%m.%d.%H.%M)'" )
        args+=( "$src/" )
        args+=( "${@}"     )
        ;;

    bm|backup-mid|bk-mid)
        prn "src: partial.mid '$src/'" "exl: ${exl_a} & ${exl_b}:"
        args+=( 'create' )
        args+=( '--stats' )
        args+=( '--progress' )
        args+=( "--exclude-from"    "$exl_b")
        args+=( "--exclude-from"    "$exl_a")
        args+=( "::'$(date +%y.%m.%d.%H.%M)'" )
        args+=( "$src/" )
        args+=( "${@}"     )
        ;;
  
    part) #"Partial Home Backup # TODO
        ;;

    *) prn "no cmd" && exit ;;
esac

prn_l

prn_args "borg" "${args[@]}${yellow}"

borg "${args[@]}"
