#!/bin/env bash
# iarom mail@iarom.org
# system maintenance pre backups

_bk_sys_pre()
{
    pkg_ls_dir="${XDG_CONFIG_HOME}/zu-ctrl/lnx-arch/cur"
    date="$(date +%y-%m)" #-%d
    pkgs_pac=$(pacman -Qqen)
    pkgs_aur=$(pacman -Qqem)
    printf "%s\n" ${pkgs_pac} > "/etc/zu-ctrl/arch-$date-pac.txt"
    printf "%s\n" ${pkgs_aur} > "/etc/zu-ctrl/arch-$date-aur.txt"
    printf "%s\n" ${pkgs_pac} > "$pkg_ls_dir/$date-pac.txt"
    printf "%s\n" ${pkgs_aur} > "$pkg_ls_dir/$date-aur.txt"
}

main()
{
    cmd=${1}
    shift 1
    case ${cmd} in
        pre)      _bk_sys_pre ;;
        l)        bkls ${@} ;;
        a)        _rst_que_y gcs ;;
        b)        _rst_que_y gcsx ;;
        x)        que_rst_x ;;
    esac
}

main "${@}"
