#!/usr/bin/env bash
# iarom mail@iarom.org
# TASK write test func to search for existence of provided env func for device
# TASK insert readline and yes confirmation prompts at key places such as mkdir

ini_v()
{
    declare -g rep=${1}
    declare -g cmd=${2}
    shift 2
    [ -f ${BHQC} ] \
        || { echo "missing bhq config; exiting"; exit; }
    source ${BHQC}
    _env_bhq
}

env_set()     { _env_${rep} && ph1 "${BHQ_DEV}: ${KY_REPO}"; }

pln() { printf "\n"; }
ph1() { printf "KY: %s\n" "${1}"; }
ph2() { pln; printf "KY: %s\n" "${1}"; }
pbd() { printf "KY: %s\n" "${1}"; }

mkgpg()
{
    pbd "no gpg dir, creating it..."
    gpgconf --kill gpg-agent
    mkdir "${GNUPGHOME}"
    ln -s "${GNUPGHOME}" ${HOME}/.gnupg
    chmod 700 "${GNUPGHOME}"
}

ini()
{
    ph1 "init kys imp/exp script"
    ini_v "${@}"
    [ "${rep}" ] || { pbd "no repo provided"; exit; }
    [ "${cmd}" ] || { pbd "no cmd provided"; exit; }
    [ -d "${GNUPGHOME}" ] || mkgpg
    set_rep
}

set_rep()
{
    case ${rep} in
    dva|dvb|dvc|dvx) env_set ;;
    #dvd) KY_REPO="$mnt_x/dvd/.key" ;;
    #dua) env_set env_dua ;;
    #dub) env_set env_dub ;;
    #duc) env_set env_duc ;;
    #rma) KY_REPO="$HOME/.config/key" ;; # remoe a : todo: systemitise using shamir's algorithm
    *)    echo "no specific environment; exiting"; exit
    esac
}

# bk exp

gpg_bk_init()
{
    ph2 "init destination"
    mkdir -p ${KY_REPO}
    chmod 700 "${KY_REPO}"
}

gpg_bk_pub()
{
    ph2 "exporting public keys"
    gpg \
        --export \
        --armor \
        --export-options backup \
        --output "${KY_REPO}/pubkeys.asc"
}

gpg_bk_prv()
{
    ph2 "exporting secret keys"
    gpg \
        --export-secret-keys \
        --armor \
        --export-options backup \
        --output "${KY_REPO}/privatekeys.asc"
}

gpg_bk_trust()
{ 
    ph2 "exporting ownertrust"
    gpg --export-ownertrust > "${KY_REPO}/ownertrust.txt"
}

gpg_bk_revocs()
{
    ph2 "exporting revocs"
    mkdir -p "$KY_REPO/revocs"
    cp -a "${GNUPGHOME}/openpgp-revocs.d/." "$KY_REPO/revocs/"
}

gpg_ls_bk()
{
    ph2 "listing files in ${KY_REPO}"
    ls -al "${KY_REPO}/"
}

gpg_bk()
{
    gpg_bk_init
    gpg_bk_pub
    gpg_bk_prv
    gpg_bk_revocs
    gpg_bk_trust
    gpg_ls_bk
}

# imp restore

gpg_imp_pub()
{
    ph2 "importing Public Keys"
    gpg --import --import-options restore "${KY_REPO}/pubkeys.asc"
}

gpg_imp_priv()
{
    ph2 "importing Private Keys"
    gpg --import --import-options restore "${KY_REPO}/privatekeys.asc"
}

gpg_imp_test()
{
    ph2 "checking that Secret keys were imported"
    gpg -K
    ph2 "checking that public keys were imported"
    gpg -k
}

gpg_imp_trust()
{
    ph2 "importing ownertrust"
    gpg --import-ownertrust --import-options restore ${KY_REPO}/ownertrust.txt
}
    
gpg_imp_finish()
{
    ph1 "Test encryption/decryption as the new user with the imported keys with:"
    pbd "gpg -er USERID"
    pbd "gpg -d"
    pbd "Don't su over to the new user; login directly via ssh or console; Otherwise decryption and signing will likely fail, if the user doesnt own the shell.."
}

gpg_imp()
{
    gpg_imp_pub
    gpg_imp_priv
    gpg_imp_test

    gpg_imp_trust
    gpg_imp_finish
}

main()
{
    ini "${@}"
    case ${cmd} in
        exp|bk|bkp)    gpg_bk ;;
        imp)           gpg_imp ;;
    esac
    pln
}

main "${@}"
