#!/bin/sh

# Iarom Madden mail@iarom.org

case $1 in
    aa)  sudo rsnapshot ahourly ;;
    dva) sudo rsnapshot -c "/etc/rsnapshot-dva.conf" alpha ;;
    dvb) sudo rsnapshot -c "/etc/rsnapshot-dvb.conf" alpha ;;
esac

