#!/bin/sh

# Iarom Madden mail@iarom.org

case $1 in
    aa)  sudo rsnapshot ahourly ;;
    dva) sudo rsnapshot -c "/etc/rsnapshot-d1.conf" alpha ;;
    dvb) sudo rsnapshot -c "/etc/rsnapshot-d2.conf" alpha ;;
esac

